export default [
    {title: 'The Shining', category: 'Horror', year: '1980', description: 'A family heads to an isolated hotel for the winter where an evil spiritual presence influences the father into violence, while his psychic son sees horrific forebodings from the past and of the future.', url: 'https://static01.nyt.com/images/2017/09/15/arts/24movie-posters8/24movie-posters8-master1050.jpg'},
    {title: 'The Strangers', category: 'Horror', year: '2008', description: 'A young couple staying in an isolated vacation home are terrorized by three unknown assailants.', url: 'http://horrorfilmcentral.com/wp-content/uploads/2015/02/strangers_ver4_xlg.jpg'},
    {title: 'RedDragon', category: 'Horror', year: '2002', description: 'A retired F.B.I. Agent with psychological gifts, is assigned to help track down "The Tooth Fairy", a mysterious serial killer. Aiding him, is imprisoned forensic psychiatrist Dr. Hannibal "The Cannibal" Lecter.', url: 'https://static.rogerebert.com/uploads/movie/movie_poster/red-dragon-2002/large_r95GzuoTcN4y63mIU9PLLWe28lH.jpg'},
    {title: 'The Lobster', category: 'Drama', year: '2015', description: 'In a dystopian near future, single people, according to the laws of The City, are taken to The Hotel, where they are obliged to find a romantic partner in forty-five days or are transformed into beasts and sent off into The Woods.', url: 'http://wp.production.patheos.com/blogs/chorusinthechaos/files/2016/06/lobstersmall.jpg'},
    {title: 'The Witch', category: 'Mystery', year: '2015', description: 'A family in 1630s New England is torn apart by the forces of witchcraft, black magic and possession.', url: 'https://3.bp.blogspot.com/-cFkGqXvV85Q/Vs3LS8K6WUI/AAAAAAAAZI0/rC46C_0Q2wg/s1600/The-Witch-Robert-Eggers-Movie-Poster-Alternate.jpg'},
    {title: 'The Human Centipede', category: 'Horror', year: '2009', description: 'A mad scientist kidnaps and mutilates a trio of tourists in order to reassemble them into a human centipede, created by stitching their mouths to each others rectums.', url: 'http://www.dvd-forum.at/img/uploaded/human-centipede-bd-hartbox.jpg'},
    {title: 'Misery', category: 'Drama', year: '1990', description: 'After a famous author is rescued from a car crash by a fan of his novels, he comes to realize that the care he is receiving is only the beginning of a nightmare of captivity and abuse.', url: 'https://static.rogerebert.com/uploads/movie/movie_poster/misery-1990/large_82I14HSRudHmxmCRbnUi1oLdltd.jpg'},
    {title: 'ClockWork Orange', category: 'Drama', year: '1971', description: 'In the future, a sadistic gang leader is imprisoned and volunteers for a conduct-aversion experiment, but it doesnt go as planned.', url: 'https://s-media-cache-ak0.pinimg.com/originals/c1/0d/57/c10d570674d35c49e811a8a024c539df.jpg'}
    // {title: 'The Imitation Game', category: 'Drama', year: '2014', description: '', url: 'https://pics.filmaffinity.com/the_imitation_game-824166913-large.jpg'}
    // {title: '', category: '', year: '', description: '', url: ''}
]
